/**
 * Document Templates for Guided Drafting
 * Contains structured templates for different document types
 */

export const DOCUMENT_TEMPLATES = {
  nda: {
    title: 'NON-DISCLOSURE AGREEMENT',
    structure: (data) => `
NON-DISCLOSURE AGREEMENT

This Non-Disclosure Agreement (the "Agreement") is entered into as of [DATE] (the "Effective Date"), by and between:

${data.parties}

(collectively, the "Parties")

RECITALS

WHEREAS, the Parties wish to explore a business opportunity of mutual interest (the "Purpose");

WHEREAS, in connection with the Purpose, the Parties may disclose to each other certain confidential and proprietary information;

NOW, THEREFORE, in consideration of the mutual covenants and agreements contained herein, the Parties agree as follows:

1. DEFINITION OF CONFIDENTIAL INFORMATION

"Confidential Information" means any and all information disclosed by either Party (the "Disclosing Party") to the other Party (the "Receiving Party") in connection with the Purpose, including but not limited to:

${data.purposeDescription}

2. OBLIGATIONS OF RECEIVING PARTY

The Receiving Party agrees to:

a) Hold and maintain the Confidential Information in strict confidence;
b) Use the Confidential Information solely for the Purpose;
c) Not disclose the Confidential Information to any third party without prior written consent;
d) Protect the Confidential Information using at least the same degree of care used to protect its own confidential information, but in no event less than reasonable care.

3. EXCLUSIONS

Confidential Information does not include information that:

a) Is or becomes publicly available through no breach of this Agreement;
b) Was rightfully in the Receiving Party's possession prior to disclosure;
c) Is independently developed by the Receiving Party without use of the Confidential Information;
d) Is rightfully received from a third party without breach of any confidentiality obligation.

${data.exclusions ? `\nAdditional Exclusions:\n${data.exclusions}` : ''}

4. TERM

This Agreement shall commence on the Effective Date and continue for a period of ${data.term} year(s). The obligations of confidentiality shall survive for ${data.confidentialityDuration} year(s) following termination.

5. RETURN OF MATERIALS

${data.returnProvision === 'Yes' ? 
  'Upon termination of this Agreement or upon request by the Disclosing Party, the Receiving Party shall promptly return or destroy all Confidential Information and certify such destruction in writing.' :
  'The Parties may retain Confidential Information subject to ongoing confidentiality obligations.'}

6. GOVERNING LAW

This Agreement shall be governed by and construed in accordance with the laws of ${data.jurisdiction}, without regard to its conflict of laws principles.

7. MISCELLANEOUS

a) Entire Agreement: This Agreement constitutes the entire agreement between the Parties concerning the subject matter hereof.
b) Amendment: This Agreement may be amended only by written agreement signed by both Parties.
c) Severability: If any provision is found unenforceable, the remainder shall continue in full force.
d) Waiver: No waiver of any provision shall constitute a waiver of any other provision.

IN WITNESS WHEREOF, the Parties have executed this Agreement as of the Effective Date.

[SIGNATURE BLOCKS]

_________________________          _________________________
[Party A Name]                     [Party B Name]
Signature                          Signature

Date: _______________              Date: _______________

---
DISCLAIMER: This document was AI-generated and requires review by a qualified attorney before use.
Generated by Lexi Legal Guardian on ${new Date().toLocaleDateString()}
`
  },

  employment: {
    title: 'EMPLOYMENT AGREEMENT',
    structure: (data) => `
EMPLOYMENT AGREEMENT

This Employment Agreement (the "Agreement") is entered into as of ${data.startDate} (the "Effective Date"), by and between:

${data.employerName} (the "Employer")

and

${data.employeeName} (the "Employee")

1. POSITION AND DUTIES

1.1 Position: The Employer hereby employs the Employee in the position of ${data.jobTitle}.

1.2 Employment Type: This is a ${data.employmentType} position.

1.3 Duties: The Employee shall perform such duties as are customarily associated with the position and as may be reasonably assigned by the Employer.

2. COMPENSATION

2.1 Base Salary: The Employee shall receive an annual base salary of $${data.compensation}, payable in accordance with the Employer's standard payroll practices.

2.2 Benefits: The Employee shall be eligible for the following benefits:
${data.benefits || 'Standard benefits package as provided to similarly situated employees.'}

3. TERM AND TERMINATION

3.1 At-Will Employment: This Agreement creates an at-will employment relationship. Either party may terminate employment at any time, with or without cause.

3.2 Notice Period: Either party may terminate this Agreement upon ${data.terminationNotice} days' written notice to the other party.

3.3 Termination for Cause: The Employer may terminate this Agreement immediately for cause, including but not limited to:
   a) Material breach of this Agreement
   b) Gross negligence or willful misconduct
   c) Conviction of a felony
   d) Violation of company policies

4. CONFIDENTIALITY

The Employee acknowledges that during employment, they will have access to confidential and proprietary information. The Employee agrees to:

a) Maintain strict confidentiality of all proprietary information
b) Not disclose confidential information to third parties
c) Return all confidential materials upon termination

5. INTELLECTUAL PROPERTY

${data.ipOwnership === 'Company owns all work product' ?
  'All work product, inventions, and intellectual property created by the Employee during employment shall be the sole and exclusive property of the Employer. The Employee hereby assigns all right, title, and interest in such work product to the Employer.' :
  'Intellectual property ownership shall be determined on a case-by-case basis in accordance with applicable law and any separate agreements.'}

${data.nonCompeteDuration ? `
6. NON-COMPETE

For a period of ${data.nonCompeteDuration} months following termination of employment, the Employee agrees not to:

a) Engage in any business that directly competes with the Employer within [GEOGRAPHIC AREA]
b) Solicit the Employer's clients or employees
c) Use confidential information to compete with the Employer

NOTE: Non-compete enforceability varies by jurisdiction. Legal review required.
` : ''}

7. GOVERNING LAW

This Agreement shall be governed by the laws of ${data.jurisdiction}.

8. ENTIRE AGREEMENT

This Agreement constitutes the entire agreement between the parties and supersedes all prior understandings.

IN WITNESS WHEREOF, the parties have executed this Agreement as of the Effective Date.

_________________________          _________________________
${data.employerName}                ${data.employeeName}
Employer Signature                  Employee Signature

Date: _______________              Date: _______________

---
DISCLAIMER: This document was AI-generated and requires review by a qualified attorney before use.
Generated by Lexi Legal Guardian on ${new Date().toLocaleDateString()}
`
  },

  // Add more templates as needed
};

export function generateDocumentFromTemplate(documentType, formData) {
  const template = DOCUMENT_TEMPLATES[documentType];
  
  if (!template) {
    throw new Error(`Template not found for document type: ${documentType}`);
  }

  return template.structure(formData);
}